# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from server_job import v1_pb2 as server__job_dot_v1__pb2


class JobServiceStub(object):
    """Used by server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunJob = channel.unary_stream(
                '/server_job.v1.JobService/RunJob',
                request_serializer=server__job_dot_v1__pb2.JobType.SerializeToString,
                response_deserializer=server__job_dot_v1__pb2.JobResponse.FromString,
                )


class JobServiceServicer(object):
    """Used by server
    """

    def RunJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunJob': grpc.unary_stream_rpc_method_handler(
                    servicer.RunJob,
                    request_deserializer=server__job_dot_v1__pb2.JobType.FromString,
                    response_serializer=server__job_dot_v1__pb2.JobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_job.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Used by server
    """

    @staticmethod
    def RunJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server_job.v1.JobService/RunJob',
            server__job_dot_v1__pb2.JobType.SerializeToString,
            server__job_dot_v1__pb2.JobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
