# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_defs.v1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_struct import v1_pb2 as custom__struct_dot_v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12node_defs.v1.proto\x12\x0cnode_defs.v1\x1a\x16\x63ustom_struct.v1.proto\"\'\n\x0eNodeDefRequest\x12\x15\n\rextension_ids\x18\x01 \x03(\t\"\xb1\x04\n\x0eNodeDefinition\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x38\n\x06inputs\x18\x04 \x03(\x0b\x32(.node_defs.v1.NodeDefinition.InputsEntry\x12:\n\x07outputs\x18\x05 \x03(\x0b\x32).node_defs.v1.NodeDefinition.OutputsEntry\x12\x12\n\nux_widgets\x18\x06 \x03(\t\x1at\n\x08InputDef\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x11\n\tedge_type\x18\x02 \x01(\t\x12-\n\x04spec\x18\x03 \x01(\x0b\x32\x1f.comfy.protobuf.v1.CustomStruct\x12\x10\n\x08required\x18\x04 \x01(\x08\x1a\x34\n\tOutputDef\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x11\n\tedge_type\x18\x02 \x01(\t\x1aT\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.node_defs.v1.NodeDefinition.InputDef:\x02\x38\x01\x1aV\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.node_defs.v1.NodeDefinition.OutputDef:\x02\x38\x01\"\x85\x01\n\x08NodeDefs\x12.\n\x04\x64\x65\x66s\x18\x01 \x03(\x0b\x32 .node_defs.v1.NodeDefs.DefsEntry\x1aI\n\tDefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.node_defs.v1.NodeDefinition:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_defs.v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODEDEFINITION_INPUTSENTRY']._options = None
  _globals['_NODEDEFINITION_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_NODEDEFINITION_OUTPUTSENTRY']._options = None
  _globals['_NODEDEFINITION_OUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_NODEDEFS_DEFSENTRY']._options = None
  _globals['_NODEDEFS_DEFSENTRY']._serialized_options = b'8\001'
  _globals['_NODEDEFREQUEST']._serialized_start=60
  _globals['_NODEDEFREQUEST']._serialized_end=99
  _globals['_NODEDEFINITION']._serialized_start=102
  _globals['_NODEDEFINITION']._serialized_end=663
  _globals['_NODEDEFINITION_INPUTDEF']._serialized_start=319
  _globals['_NODEDEFINITION_INPUTDEF']._serialized_end=435
  _globals['_NODEDEFINITION_OUTPUTDEF']._serialized_start=437
  _globals['_NODEDEFINITION_OUTPUTDEF']._serialized_end=489
  _globals['_NODEDEFINITION_INPUTSENTRY']._serialized_start=491
  _globals['_NODEDEFINITION_INPUTSENTRY']._serialized_end=575
  _globals['_NODEDEFINITION_OUTPUTSENTRY']._serialized_start=577
  _globals['_NODEDEFINITION_OUTPUTSENTRY']._serialized_end=663
  _globals['_NODEDEFS']._serialized_start=666
  _globals['_NODEDEFS']._serialized_end=799
  _globals['_NODEDEFS_DEFSENTRY']._serialized_start=726
  _globals['_NODEDEFS_DEFSENTRY']._serialized_end=799
# @@protoc_insertion_point(module_scope)
