# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_struct.v1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ustom_struct.v1.proto\x12\x11\x63omfy.protobuf.v1\"\x94\x01\n\x0c\x43ustomStruct\x12;\n\x06\x66ields\x18\x01 \x03(\x0b\x32+.comfy.protobuf.v1.CustomStruct.FieldsEntry\x1aG\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.comfy.protobuf.v1.Value:\x02\x38\x01\"\x8d\x02\n\x05Value\x12\x32\n\nnull_value\x18\x01 \x01(\x0e\x32\x1c.comfy.protobuf.v1.NullValueH\x00\x12\x16\n\x0cnumber_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x37\n\x0cstruct_value\x18\x05 \x01(\x0b\x32\x1f.comfy.protobuf.v1.CustomStructH\x00\x12\x32\n\nlist_value\x18\x06 \x01(\x0b\x32\x1c.comfy.protobuf.v1.ListValueH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x42\x06\n\x04kind\"5\n\tListValue\x12(\n\x06values\x18\x01 \x03(\x0b\x32\x18.comfy.protobuf.v1.Value*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x42\x87\x01\n\x19org.comfycreator.protobufB\x11\x43ustomStructProtoP\x01Z)comfycreator.com/protobuf/custom_structpb\xf8\x01\x01\xa2\x02\x02\x43\x43\xaa\x02!ComfyCreator.Protobuf.CustomTypesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_struct.v1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031org.comfycreator.protobufB\021CustomStructProtoP\001Z)comfycreator.com/protobuf/custom_structpb\370\001\001\242\002\002CC\252\002!ComfyCreator.Protobuf.CustomTypes'
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._options = None
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_NULLVALUE']._serialized_start=523
  _globals['_NULLVALUE']._serialized_end=550
  _globals['_CUSTOMSTRUCT']._serialized_start=46
  _globals['_CUSTOMSTRUCT']._serialized_end=194
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_start=123
  _globals['_CUSTOMSTRUCT_FIELDSENTRY']._serialized_end=194
  _globals['_VALUE']._serialized_start=197
  _globals['_VALUE']._serialized_end=466
  _globals['_LISTVALUE']._serialized_start=468
  _globals['_LISTVALUE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
